services:
  controller:
    build:
      dockerfile: docker/Dockerfile.controller
      context: ../
      tags:
        - mj0nez/jenkins-ci:${JENKINS_VERSION}-controller
    image: mj0nez/jenkins-ci:${JENKINS_VERSION}-controller

  agent-debian:
    build:
      dockerfile: docker/Dockerfile.agent-debian
      context: ../
      target: all-mighty
      tags:
        - mj0nez/jenkins-agent:${JENKINS_VERSION}-bookworm
    image: mj0nez/jenkins-agent:${JENKINS_VERSION}-bookworm

  # # TODO: installation of Docker
  # agent-alpine:
  #   build:
  #     dockerfile: docker/Dockerfile.agent-alpine
  #     context: ../
  #     target: alpine
  #     tags:
  #       - mj0nez/jenkins-agent:${JENKINS_VERSION}-alpine
  #   image: mj0nez/jenkins-agent:${JENKINS_VERSION}-alpine
