# syntax=docker/dockerfile:1
ARG GOLANG_VERSION="1.24.1"
FROM docker:28.2.2-dind-alpine3.21 AS dind

FROM jenkins/inbound-agent:bookworm-jdk21 AS base

USER root

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    tree \
    jq \
    parallel \
    sshpass \
    zip \
    unzip \
    time \
    iputils-ping \
    traceroute \
    dnsutils \
    netcat-openbsd \
    iptables \
    pigz \
    xz-utils \
    # docker-dind
    btrfs-progs \
    e2fsprogs \
    git \
    iptables \
    iproute2 \
    net-tools \
    openssl \
    pigz \
    xfsprogs \
    # dev
    htop \
    procps \
    findutils \
    # cgo
    g++ \
    gcc \
    libc6-dev \
    make \
    pkg-config \
    ; \
    rm -rf /var/lib/apt/lists/*

# the docker installation follows the dind project build,
# which we set on-top of the jenkins inbound-agent
RUN set -eux; \
    groupadd -g 2375 -r docker

# set up subuid/subgid so that "--userns-remap=default" works out-of-the-box
RUN set -eux; \
    groupadd -r dockremap; \
    adduser --system --ingroup dockremap dockremap; \
    echo 'dockremap:165536:65536' >> /etc/subuid; \
    echo 'dockremap:165536:65536' >> /etc/subgid

# https://github.com/docker-library/docker/pull/166
#   dockerd-entrypoint.sh uses DOCKER_TLS_CERTDIR for auto-generating TLS certificates
#   docker-entrypoint.sh uses DOCKER_TLS_CERTDIR for auto-setting DOCKER_TLS_VERIFY and DOCKER_CERT_PATH
# (For this to work, at least the "client" subdirectory of this path needs to be shared between the client and server containers via a volume, "docker cp", or other means of data sharing.)
ENV DOCKER_TLS_CERTDIR=/certs
# also, ensure the directory pre-exists and has wide enough permissions for "dockerd-entrypoint.sh" to create subdirectories, even when run in "rootless" mode
RUN mkdir /certs /certs/client && chmod 1777 /certs /certs/client

# copy binaries for docker & co
COPY --from=dind /usr/local/bin/ /usr/local/bin/
COPY --from=dind /usr/local/libexec/docker/cli-plugins /usr/local/libexec/docker/cli-plugins

VOLUME /var/lib/docker

# fix nested tini warning
ENV TINI_SUBREAPER=

COPY --chown=jenkins:jenkins docker/basefs /

# USER jenkins

ENTRYPOINT [ "docker-init", "--", "/usr/local/bin/entrypoint-cstm.sh" ]
CMD ["/usr/local/bin/jenkins-agent"]


# the nomad installation follows the multani/docker-nomad project,
# we download the oss binary (musl is enterprise only) and add it to our agent
FROM debian:12.11-slim AS nomad-loader


ARG NOMAD_VERSION
ARG TARGETOS=linux
ARG TARGETARCH=amd64

# nomad
ADD https://releases.hashicorp.com/nomad/${NOMAD_VERSION}/nomad_${NOMAD_VERSION}_${TARGETOS}_${TARGETARCH}.zip \
    nomad_${NOMAD_VERSION}_${TARGETOS}_${TARGETARCH}.zip
ADD https://releases.hashicorp.com/nomad/${NOMAD_VERSION}/nomad_${NOMAD_VERSION}_SHA256SUMS \
    nomad_${NOMAD_VERSION}_SHA256SUMS
ADD https://releases.hashicorp.com/nomad/${NOMAD_VERSION}/nomad_${NOMAD_VERSION}_SHA256SUMS.sig \
    nomad_${NOMAD_VERSION}_SHA256SUMS.sig

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
    gnupg \
    unzip \
    && GNUPGHOME="$(mktemp -d)" \
    && export GNUPGHOME \
    && gpg --keyserver pgp.mit.edu --keyserver keys.openpgp.org --keyserver keyserver.ubuntu.com --recv-keys "C874 011F 0AB4 0511 0D02 1055 3436 5D94 72D7 468F" \
    && gpg --batch --verify nomad_${NOMAD_VERSION}_SHA256SUMS.sig nomad_${NOMAD_VERSION}_SHA256SUMS \
    && grep nomad_${NOMAD_VERSION}_${TARGETOS}_${TARGETARCH}.zip nomad_${NOMAD_VERSION}_SHA256SUMS | sha256sum -c \
    && unzip -d /tmp/nomad nomad_${NOMAD_VERSION}_${TARGETOS}_${TARGETARCH}.zip \
    && chmod +x /tmp/nomad \
    && rm -rf "$GNUPGHOME" nomad_${NOMAD_VERSION}_${TARGETOS}_${TARGETARCH}.zip nomad_${NOMAD_VERSION}_SHA256SUMS nomad_${NOMAD_VERSION}_SHA256SUMS.sig


# # s3 compatible cli-tool from minio
FROM minio/mc:RELEASE.2025-04-08T15-39-49Z AS mc 

# go we can fetch from the official docker image
ARG GOLANG_VERSION
FROM golang:${GOLANG_VERSION}-bookworm AS go

FROM base AS all-mighty

# python
ARG UV_VERSION
ARG PYTHON_311_VERSION
ARG PYTHON_312_VERSION
ARG PYTHON_313_VERSION

ENV XDG_BIN_HOME=/usr/local/bin \
    UV_NO_MODIFY_PATH=1

RUN curl -LsSf https://astral.sh/uv/${UV_VERSION}/install.sh | bash -s -- -v
RUN uv --version \
    && uv python install \
    ${PYTHON_311_VERSION} \
    ${PYTHON_312_VERSION} \
    ${PYTHON_313_VERSION}

# go
ARG GOLANG_VERSION
ARG GOLANGCI_LINT_VERSION

ENV GOLANG_VERSION="${GOLANG_VERSION}"
ENV GOTOOLCHAIN="local"
# defaults to $HOME/go but we want under ~/.cache/go to make caching of dependencies easier
ENV GOPATH="/root/.cache/go"
# move the build cache to an ephemeral path
ENV GOCACHE="/tmp/go-build"
ENV PATH="$GOPATH/bin:/usr/local/go/bin:$PATH"

# TODO: it seems that the '--link' option crashes the actions run
# it could be that adding intermediate layers per copy directive requires just to much resources 
# for public runners
COPY --from=go /usr/local/go /usr/local/go

# binary will be /usr/local/go/bin/golangci-lint, normally this is for official binaries
# but because we want to cache our tools and not overwrite this one, it should be ok
RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b /usr/local/go/bin v${GOLANGCI_LINT_VERSION}
RUN go version && \
    golangci-lint version

# nomad
COPY --from=nomad-loader --chown=jenkins:jenkins /tmp/nomad/nomad /usr/local/bin/nomad

COPY --from=mc /usr/bin/mc /usr/bin/mc
COPY --from=mc /licenses/CREDITS /licenses/CREDITS
COPY --from=mc /licenses/LICENSE /licenses/LICENSE