# syntax=docker/dockerfile:1
FROM jenkins/inbound-agent:bookworm-jdk21 AS base

USER root

RUN apt-get update \
    && apt-get install -y lsb-release
RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
    https://download.docker.com/linux/debian/gpg

RUN echo "deb [arch=$(dpkg --print-architecture) \
    signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
    https://download.docker.com/linux/debian \
    $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

RUN apt-get update \
    && apt-get install -y \
        docker-ce \
        docker-ce-cli \
        containerd.io \
        docker-buildx-plugin \
        docker-compose-plugin

COPY --chown=jenkins:jenkins docker/basefs /

# USER jenkins

ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]

FROM base AS all-mighty

ENV PATH="/root/.local/bin:$PATH"

# python related
RUN curl -LsSf https://astral.sh/uv/install.sh | bash

RUN uv --version \
    && uv python install \
        3.11 \
        3.12 \
        3.13
