networks:
  jenkins:

services:
  controller:
    build:
      dockerfile: docker/Dockerfile.controller
      context: ../
      tags:
        - mj0nez/jenkins-ci:${JENKINS_VERSION}
        - mj0nez/jenkins-ci:${APP_VERSION}
    image: mj0nez/jenkins-ci:${APP_VERSION}

  agent-debian:
    build:
      dockerfile: docker/Dockerfile.agent-debian
      context: ../
      args:
        NOMAD_VERSION: ${NOMAD_VERSION}
        GOLANG_VERSION: ${GOLANG_VERSION}
        UV_VERSION: ${UV_VERSION}
        PYTHON_311_VERSION: ${PYTHON_311_VERSION}
        PYTHON_312_VERSION: ${PYTHON_312_VERSION}
        PYTHON_313_VERSION: ${PYTHON_313_VERSION}
      target: all-mighty
      tags:
        - mj0nez/jenkins-agent:${APP_VERSION}-bookworm-all-mighty
        - mj0nez/jenkins-agent:${APP_VERSION}-bookworm-all-mighty-${JENKINS_VERSION}
        - mj0nez/jenkins-agent:bookworm-all-mighty-${JENKINS_VERSION}
        - mj0nez/jenkins-agent:bookworm-all-mighty
    image: mj0nez/jenkins-agent:${APP_VERSION}-bookworm-all-mighty

  # agent-alpine:
  #   build:
  #     dockerfile: docker/Dockerfile.agent-alpine
  #     context: ../
  #     args:
  #       NOMAD_VERSION: ${NOMAD_VERSION}
  #     target: all-mighty
  #     tags:
  #       - mj0nez/jenkins-agent:${APP_VERSION}-alpine-all-mighty
  #       - mj0nez/jenkins-agent:${APP_VERSION}-alpine-all-mighty-${JENKINS_VERSION}
  #       - mj0nez/jenkins-agent:alpine-all-mighty-${JENKINS_VERSION}
  #       - mj0nez/jenkins-agent:alpine-all-mighty
  #   image: mj0nez/jenkins-agent:${APP_VERSION}-alpine-all-mighty
