# syntax=docker/dockerfile:1
FROM jenkins/inbound-agent:alpine3.21-jdk21 AS base


FROM docker:28.0.1-dind-alpine3.21 AS agent

ARG user=jenkins
ARG group=jenkins
ARG uid=1000
ARG gid=1000

RUN addgroup -g "${gid}" "${group}" \
    && adduser -h /home/"${user}" -u "${uid}" -G "${group}" -D "${user}" || echo "user ${user} already exists."

ARG AGENT_WORKDIR=/home/"${user}"/agent

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'
ENV TZ=Etc/UTC

RUN apk add --no-cache \
    curl \
    bash \
    git \
    git-lfs \
    musl-locales \
    openssh-client \
    openssl \
    procps \
    tzdata \
    tzdata-utils \
    && rm -rf /tmp/*.apk /tmp/gcc /tmp/gcc-libs.tar* /tmp/libz /tmp/libz.tar.xz /var/cache/apk/*

COPY --from=base --chown="${user}":"${group}" /usr/share/jenkins/agent.jar /usr/share/jenkins/agent.jar
RUN chmod 0644 /usr/share/jenkins/agent.jar \
    && ln -sf /usr/share/jenkins/agent.jar /usr/share/jenkins/slave.jar


ENV JAVA_HOME=/opt/java/openjdk
COPY --from=base "$JAVA_HOME" "$JAVA_HOME"
ENV PATH="${JAVA_HOME}/bin:${PATH}"

USER "${user}"
ENV AGENT_WORKDIR="${AGENT_WORKDIR}"
RUN mkdir -p /home/"${user}"/.jenkins && mkdir -p "${AGENT_WORKDIR}"

VOLUME /home/"${user}"/.jenkins
VOLUME "${AGENT_WORKDIR}"
WORKDIR /home/"${user}"
ENV USER=${user}


## Inbound Agent image target
FROM agent AS inbound-agent

ARG user=jenkins

USER root
COPY --from=base /usr/local/bin/jenkins-agent /usr/local/bin/jenkins-agent
RUN chmod +x /usr/local/bin/jenkins-agent &&\
    ln -s /usr/local/bin/jenkins-agent /usr/local/bin/jenkins-slave

COPY docker/basefs /
ENV TINI_SUBREAPER=

ENTRYPOINT [ "docker-init", "--", "/usr/local/bin/entrypoint-cstm.sh" ]
CMD ["/usr/local/bin/jenkins-agent"]

#
FROM inbound-agent AS all-mighty

ENV XDG_BIN_HOME=/usr/local/bin \
    UV_NO_MODIFY_PATH=1

# python related
RUN curl -LsSf https://astral.sh/uv/install.sh | bash -s -- -v

RUN uv --version \
    && uv python install \
    3.11 \
    3.12 \
    3.13
